name = "BEASTSimulation"
uuid = "66356b0f-fbef-4e1b-82cb-aec6d487ef3b"
authors = ["Gabe Hassler <gabriel.w.hassler@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
